#!/bin/bash

# Kills named singularity instance.
# Author: Callum
# https://github.com/nesi/nesi-virtual-desktops

module load Singularity/3.5.2
module unload XALT/NeSI

#Location of this script
echo "$@"

# Where files are saved in user home.
help() {
cat << EndOfHelp
[1m$CWD[0m

[1mSYNOPSIS[0m
        $CWD [-h ] < display-port >

[1mDESCRIPTION[0m
        Kills Virtual Desktop.

[1mPARAMETERS[0m

    -h --help               This is help.

EndOfHelp
}

parse_input() {
        
    # Parse flags + port
    if [[ $# -gt 1 ]];then
        echo "Too many arguments '${1}', -h for help."  >&2
    fi
    if [[ $1 == "-h"  ]] || [[ $1 == "--help" ]];then
        help "$0"
        exit 0
    fi
    name="$1"
}

kill_vnc(){
    display_port=$(($(echo "${name}" | grep -o '[^_]*$')-5900))
    #singularity instance list
    #singularity exec --cleanenv instance://${name} vncserver -list #":"  # || singularity instance stop "${name}"
    singularity exec --cleanenv instance://${name} vncserver -v -kill :$name
    singularity instance stop ${name}
    rm -vf "/tmp/.X$display_port-lock"
    rm -vf "$HOME"/.vnc/*"${name}".pid
    exit 0
}

main() {
    parse_input "$@"
    kill_vnc
}

main "$@"

