#!/bin/bash -e

# Provides simple inteface for setting up VNC sessions, connecting, hosting noVNC etc etc.
# Author: Callum
# https://github.com/nesi/nesi-virtual-desktops


# TODO: Creates a web socket connecting port to VNC server

module purge > /dev/null  2>&1
module load Python Singularity/3.6.1 -q 
module unload XALT/NeSI -q


#Location of this script
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
websockify_home="$root/websockify_modified"
novnc_home="$root/noVNC_modified"


# Where files are saved in user home.

help() {
cat << EndOfHelp
[1m$CWD[0m

[1mSYNOPSIS[0m
        $CWD [-h -v] <display-port>

[1mDESCRIPTION[0m
        Opens shell to VDT session.

[1mPARAMETERS[0m

    -h --help               This is help.

    -v --verbose

EndOfHelp
}

cleanup() {
    pkill --signal 15 -P $$
}

parse_input() {
    if [[ $# -lt 1 ]];then
        if [[ $1 == "-h"  ]] || [[ $1 == "--help" ]];then
            help "$0"
            exit 0
        fi
        echo "Not enough arguments."  >&2
        help "$0"
        exit 1
    fi
    # Parse flags + port
    while [[ $# -gt 1 ]];do
        case $1 in
            -h|--help)
                help "$0"
                shift
            ;;
            -v|--verbose)
                verbose="--verbose"
                shift
            ;;
            *)
                echo "Unknown option '${1}', -h for help."  >&2
                exit 1
            ;;
        esac
    done
    socket_port="$1"
}

connect_vnc(){
    singularity ${verbose} shell instance://$socket_port
}
main() {
    parse_input "$@"
    connect_vnc
    return 0
}
trap cleanup INT
main "$@"

