#!/bin/bash

# Lists named singularity instance.
# Author: Callum
# https://github.com/nesi/nesi-virtual-desktops

root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export VDT_LOCKFILES=${VDT_LOCKFILES:-"$root/lockfiles"}

module purge > /dev/null  2>&1
module load Python Singularity/3.5.2 -q
module unload XALT/NeSI -q

# Where files are saved in user home.
help() {
cat << EndOfHelp
[1mNAME[0m
        $(basename "$0") - List virtual desktops.

[1mSYNOPSIS[0m
        $(basename "$0") [-h -n -v ] < display-port >

[1mDESCRIPTION[0m
        Lists VNC sessions

[1mPARAMETERS[0m

    -n --noheader           Print without header.

    -h --help               This is help.

    -v --verbose            Display more information.

EndOfHelp
}

parse_input() {
    while [[ $# -gt 0 ]];do
        case $1 in
            -n|--noheader)
                noheader="true"
                shift
            ;;
            -h|--help)
                help "$0"
                exit 0
                shift
            ;;
            -v|--verbose)
                verbose="-v"
                shift
            ;;
            *)
                echo "$@"
                echo "Unknown option '${1}', -h for help."  >&2
                help "$0"
                exit 1
            ;;
        esac
    done
}

list_vnc(){
    
    #$echo $vnc_pid_root
    #if [["$verbose"]]; then echo "Using "
    _uniq_hosts=()
    _lockfiles=($(find $VDT_LOCKFILES  -type f  -user $(whoami)))
    vecho "Found lockfiles '${_lockfiles[*]}'"
    
    #vnc_list=( $(ls "${vnc_pid_root:="${HOME}/.vnc"}"/*.pid 2> /dev/null || true) )
    #echo "${vnc_list[@]}"
    for session in  ${_lockfiles[@]} ; do
        #echo $session
        #_display_port=$(echo "${session}" | sed -e 's/.*:\([0-9]*\).pid/\1/')
        #_hostname=$(echo "$session" | sed -e 's/.*\/\(.*\):.*/\1/')
        
        _uniq_hosts+=( "$(echo $session | cut -d "." -f2 | cut -d ":" -f1)" )
        #echo "${_display_port} ${_hostname}"
        #echo "${session}"
        
    done
    # Remove duplicates
    _uniq_hosts=($(printf "%s\n" "${_uniq_hosts[@]}" | sort -u | tr '\n' ' '))
    vecho "Unique hosts '${_uniq_hosts[*]}'"

    #_intances+=( $(singularity instance list | tail -n +2 | tr -s " " "\|" | tr '\n' '${HOSTNAME} \n' &) )
    if [[ ! "$noheader" ]]; then printf "%12s %12s %12s %20s\n" "Name" "PID" "Host" "Image";fi
    
    #singularity instance list | tail -n +2 |awk -v host="$(hostname)" '{printf "%12s %12s %12s %20s\n", $1, $2, host, $3}'
    background_pid=()
    # Check in background
    for host in "${_uniq_hosts[@]}" ; do
        check_on_host ${host} &
        background_pid+=( $! )
    done

    # wait for all pids
    for pid in ${background_pid[*]}; do
        wait $pid
    done
    #printf "${_intances[@]}"
    exit 0
}

check_on_host(){
    if [[ "${1}" != "$(hostname)" ]];then 
        ssh_cmd="ssh -q ${host} module load Singularity/${EBVERSIONSINGULARITY};"
    else
        ssh_cmd=""
    fi
    
    instances_in_host=( $($ssh_cmd singularity instance list | tail -n +2) )  #|awk -v host="$(hostname)" '{printf "%12s %12s %12s %20s\n", $1, $2, host, $3}'" #|| find ${VDT_LOCKFILES}/*.${host}* -user ${USER} -exec rm ${verbose} -f {} \; &2>/dev/null
    # Find and remove faulty lockfiles.
    if [[ "${#instances_in_host[@]}" -lt 1 ]];then 
        find "$VDT_LOCKFILES" -type f -user "$(whoami)" -name *${1}* -exec rm ${verbose} -f {} \;
    else
        for instance in "${instances_in_host[@]}";do
            mapfile -t instance_array <<< "$instance"
            echo "${instance_array[$1]}"
            #touch ${instance}
        done 
    fi
}

main() {
    parse_input "$@"
    list_vnc "$@"
}
vecho () {
    # For verbose print.
    if [[ $verbose ]]; then
        echo "$@"
    fi
}

vex () {
    # For verbose print.
    if [[ $verbose ]]; then
        echo "$@"
    fi
    $@
}
main "$@"

