#!/bin/bash -e

# Kills named singularity instance.
# Author: Callum
# https://github.com/nesi/nesi-virtual-desktops

module purge > /dev/null  2>&1
module load Python Singularity/3.5.2 -q 
module unload XALT/NeSI -q

root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"    # Location of this script 
VDT_LOCKFILES=${VDT_LOCKFILES:-"$root/lockfiles"} 


# Where files are saved in user home.
help() {
cat << EndOfHelp
[1mNAME[0m
        $(basename "$0") - Kill a virtual desktop.

[1mSYNOPSIS[0m
        $(basename "$0") [-h ] < display-port >

[1mDESCRIPTION[0m
        Kills Virtual Desktop.

[1mPARAMETERS[0m

    -h --help               This is help.

    -v --verbose               This is help.

[1mSEE ALSO[0m

EndOfHelp
}

parse_input() {
    while [[ $# -gt 1 ]];do
        case $1 in
        -h|--help)
                help "$0"
                shift
            ;;
        -v|--verbose)
            verbose="-v"
            #set -x
            shift
        ;;
        *)
                echo "Unknown option '${1}', -h for help."  >&2
                exit 1
            ;;
        esac
    done
    # # Parse flags + port
    # if [[ $# -gt 1 ]];then
    #     echo "Too many arguments '${1}', -h for help."  >&2
    # fi
    
    export VDT_INSTANCE_NAME="$1"
}

kill_vnc(){
    # See if any lockfiles exist with this name.
    _lockfiles=( $(find $VDT_LOCKFILES -type f -name ${VDT_INSTANCE_NAME}.* -user $(whoami)) )
    vecho "Found lockfiles '${_lockfiles[*]}'"
    sshcmd=""
    # See if any lockfiles exist with this name.
    if [[ ${#_lockfiles[@]} -gt 0 ]];then 
        hostname="$(echo "${_lockfiles[0]}" | cut -d "." -f2 | cut -d ":" -f1)"
        vecho "Session:'${_lockfiles[0]}' Hostname:'$hostname'"
        if [[ $hostname != $(hostname) ]];then 
            sshcmd="ssh ${verbose} ${hostname} module load Singularity/${EBVERSIONSINGULARITY};"
        fi
        rm -f $verbose "${VDT_LOCKFILES}/${_lockfiles[0]}" #>/dev/null 2>&1
    fi
    # If no lockfiles, try blind.
    vex ${sshcmd} singularity instance stop ${VDT_INSTANCE_NAME} >/dev/null 2>&1 || echo "No instance named '$VDT_INSTANCE_NAME' on ${hostname:-$(hostname)}"; return 1
    echo "Instance '${VDT_INSTANCE_NAME}' killed." 
    #echo "$?"
    #|| echo "No instance named '$VDT_INSTANCE_NAME'" & return 1
    #echo "Instance '${VDT_INSTANCE_NAME}' killed." 
}

vecho () {
    # For verbose print.
    if [[ $verbose ]]; then
        echo "$LINENO:$*"
    fi
}

vex () {
    # For verbose exectute.
    if [[ $verbose ]]; then
        echo "$LINENO:$*"
    fi
    $@
}

main() {
    parse_input "$@"
    kill_vnc
}

main "$@"
