name: Build rocky8vdt image
on:
  workflow_dispatch:
  push:
    paths:
      - "sif/rocky8vdt.def"
env:
  APPTAINER_SRC: "https://github.com/apptainer/apptainer/releases/download/v1.1.0-rc.2/apptainer_1.1.0-rc.2_amd64.deb"
jobs:
  build-rocky8vdt:
    uses: ./.github/workflows/build.yml@v1
    with:
        image-name: rocky8vdt
