
# TODO ensure artefacts have limited lifetime on github packages
# TODO cancel current workflow if new run on the same branch, see https://stackoverflow.com/a/67939898
name: Build container image

on:
  workflow_dispatch:
  push:
    paths:
      - 'sif/**'
    tags:
      - '*'
env:
  APPTAINER_SRC: "https://github.com/apptainer/apptainer/releases/download/v1.1.0-rc.2/apptainer_1.1.0-rc.2_amd64.deb"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y wget
      - name: Install Apptainer
        run: |
          wget $APPTAINER_SRC
          sudo apt-get install -y ./${APPTAINER_SRC##*/}"
      - uses: actions/checkout@v3
      - name: Build First Container
      - run: export IMAGE_NAME="rocky8"
      - run: sudo apptainer build ${IMAGE_NAME}.sif ${IMAGE_NAME}.def
        working-directory: ./sif        
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push conf/rocky8.sif "oras://ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:latest
      - name: Build Second Container
      - run: export IMAGE_NAME="rocky8vis"
      - run: sudo apptainer build ${IMAGE_NAME}.sif ${IMAGE_NAME}.def
        working-directory: ./sif        
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push conf/rocky8.sif "oras://ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:latest
      - name: Build Third Container
      - run: export IMAGE_NAME="rocky8vdt"
      - run: sudo apptainer build ${IMAGE_NAME}.sif ${IMAGE_NAME}.def
        working-directory: ./sif        
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push conf/rocky8.sif "oras://ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:latest
